version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "bewise_ai"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - bewise-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mycustomnetwork  


  bewise_ai:
    build: ./
    container_name: bewise_ai
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - mycustomnetwork


volumes:
  bewise-data:


networks:
  mycustomnetwork:
    driver: bridge
    